<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_MotorUnit" Id="{601e1689-e1e8-4aee-bef9-ee2ebd1bdcb7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MotorUnit
VAR_INPUT
    CmdRun   : BOOL;   // Command from controller
    MotorOK  : BOOL;   // from sensor Motor health input
	RunningIn : BOOL;  // From sensor (conveyor running feedback)
END_VAR
VAR_OUTPUT
    MotorRun : BOOL;   // Output to motor actuator
    IsRunning: BOOL;   // Sensor input: motor running
END_VAR
VAR
    //
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Simple interlock
MotorRun   := CmdRun AND MotorOK ;
IsRunning  := RunningIn;]]></ST>
    </Implementation>
    <LineIds Name="FB_MotorUnit">
      <LineId Id="21" Count="1" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>